import 'package:hive_flutter/hive_flutter.dart';
import 'package:railpantry/models/inventory_item.dart';

class StorageService {
  static const String inventoryBoxName = 'inventory_items';

  static Future<void> init() async {
    await Hive.initFlutter();
    // Register adapters for Hive
    // Hive.registerAdapter(InventoryItemAdapter()); // Generated by build_runner
    await Hive.openBox<InventoryItem>(inventoryBoxName);
  }

  static Box<InventoryItem> getInventoryBox() {
    return Hive.box<InventoryItem>(inventoryBoxName);
  }

  // Cache inventory for offline use
  static Future<void> cacheInventory(List<InventoryItem> items) async {
    final box = getInventoryBox();
    await box.clear();
    for (var item in items) {
      await box.put(item.id, item);
    }
  }

  // Retrieve cached inventory
  static List<InventoryItem> getCachedInventory() {
    return getInventoryBox().values.toList();
  }
}
